<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/icon/rfs_logo_black_sm.png">

    <title>Thailand Healthcare Facility Management Excellence Seminar</title>

    <!-- Bootstrap core CSS -->
    <!-- <link href="/css/bootstrap.min.css" rel="stylesheet"> -->
    <link href="/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/starter-template.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <!-- #009999green, #3b5998blue -->
    
  <style type="text/css">
  @font-face {
	font-family: 'Conv_FreesiaUPC';
	src: url('/fonts/FreesiaUPC.eot');
	src: local('☺'), url('/fonts/FreesiaUPC.woff') format('woff'), url('/fonts/FreesiaUPC.ttf') format('truetype'), url('/fonts/FreesiaUPC.svg') format('svg');
	font-weight: normal;
	font-style: normal;
  }
  @font-face {
	font-family: 'Conv_Kanit-Regular';
	src: url('/fonts/Kanit-Regular.eot');
	src: local('☺'), url('/fonts/Kanit-Regular.woff') format('woff'), url('/fonts/Kanit-Regular.ttf') format('truetype'), url('/fonts/Kanit-Regular.svg') format('svg');
	font-weight: normal;
	font-style: normal;
  }
    .navbar-custom > li > a{
      color: white!important;
      font-weight:bold;
      font-family: Conv_Kanit-Regular;
      font-size:large;
      background-color: ##18213A;
    }
    .navbar-custom > li > a:hover{
      color: #139DB6!important;
      font-weight:bold;
      font-family: Conv_Kanit-Regular;
      font-size:large;
      background-color: white;
    }
    
    .dropdown-menu > li > a{
      color: #253C80!important;
      font-weight:bold;
      font-family: Conv_Kanit-Regular;
      font-size:large;
      background-color: #white;
    }
    .dropdown-menu > li > a:hover{
      color: white;!important;      
      font-weight:bold;
      font-family: Conv_Kanit-Regular;
      font-size:large;
      background-color: lightgray;
    }
   
    body {
	  background-color: #FFF;
    }

  </style>
  </head>

  <body>	
  	<div class="container">
      <!-- <div class="header clearfix"> -->
        <!-- <font color="#3b5998">
        <font color="white" face="FreesiaUPC" size="large" onmouseover="green">
        <!--<h3><font color="#3b5998"></h3><img src="/pic/logo.jpg"></h3>-->
      <!-- </div align="center"> -->
        <!--<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="background-color:#3b5998; color: #FFF;">-->
        <!--<nav class="navbar navbar-default" role="navigation" style="background-color:#3b5998; color: #FFF;">-->
        <!--<nav class="navbar navbar-default" role="navigation" style="background-color:#253C80; color: #FFF; opacity: 1">-->
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="background-color:#253C80; color: #FFF; opacity: 1">
        <!--<nav class="navbar navbar-inverse navbar-top">-->	
          <div class="container-fluid">
          	<a class="navbar-brand" href="#">
               <img src="/icon/logo_small.png" width="70%" align="left">
            </a>
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span> 
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <!--<a class="navbar-brand" href="#">Nitigorn Industry Co.,Ltd. & Thanan Polypack Co.,Ltd.</a>-->
            </div>          
            
            <div class="collapse navbar-collapse pull-left navbar-btn">
            	<!--<ul class="nav navbar-nav navbar-custom">-->
            	<ul class="nav nav-pills pull-right navbar-custom">	
            		<li><a href="/index">หน้าแรก</a></li>
            		<li><a href="/index/about" style="font: Conv_Kanit-Regular">เกี่ยวกับRFS</a></li>
            		
            		<li class="dropdown">
                       <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">ข้อมูลสัมมนา <span class="caret"></span></a>
                       <ul class="dropdown-menu">
                          <li><a href="/index/intro">ความเป็นมา</a></li>
                          <li><a href="/index/schedule">กำหนดการ</a></li>
                          <li><a href="/index/place">สถานที่จัดงาน</a></li>
                          <li role="separator" class="divider"></li>
                          <li><a href="/index/lecturer">วิทยากร</a></li>
                       
                          <!-- <li role="separator" class="divider"></li> -->
                          <li><a href="#">เอกสารประกอบ</a></li>
                          <!-- <li role="separator" class="divider"></li> -->
                          <li><a href="#">ภาพบรรยากาศงานครั้งที่ผ่านมา</a></li>
                          
                       </ul>
                    </li>
                    
            		<li class="dropdown">
                       <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">ลงทะเบียน <span class="caret"></span></a>
                       <ul class="dropdown-menu">
                          <!--<li><a href="#">ลงทะเบียน online</a></li>-->
                          <li><a href="#">Download ใบสมัคร</a></li>
                          <!--<li><a href="#">ตรวจสอบสถานะ</a></li>-->
                       </ul>
                    </li>
            		<li><a href="/index/faqs">ถาม-ตอบ</a></li>
            		<li><a href="/index/contact">ติดต่อเรา</a></li>
            	</ul>
            	
            </div>
                <!--<p style="font-size: 1px">&nbsp;</p>-->
                <p align="right" style="font-family: Conv_Kanit-Regular; font-size: 16px; font-weight: bold; color: white; font-style: normal;">
                       <?php
                          /*
                          $login_id = $_SESSION['login_id'];                
                          //print'<a href="/idex/user" style="color:white">';
                          print'You are login as: '.$login_id;
                          print'</a>';
						   */
			           ?>
                       <!--<a href="/manage/index">
                       	  <button type="button" class="btn btn-primary" style="font-family: Conv_Kanit-Regular; font-size: 18px; font-weight: bold; color: white; font-style: normal;">login</button>
                       </a>-->
                <!--</p>-->
            <!--
            <div class="navbar-body">
              <ul class="nav nav-pills pull-right navbar-custom">	
                <!--<li role="presentation" class="active"><a href="/index">Home</a></li>
                <li role="presentation"><a href="/index">Home</a></li>
                <li role="presentation"><a href="/index/about">About</a></li>
                <li role="presentation"><a href="/index/product">Product</a></li>
                <li role="presentation"><a href="/index/quality">Quality</a></li>
                <li role="presentation"><a href="/index/contact">Contact</a></li>
                <li role="presentation"><a href="#">TH/EN</a></li>
              </ul>  
            </div>   
            -->  
          </div>
        </nav>   
        </font>
    </div> 
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p style="text-align: center"><img src="/icon/pic2.jpg" width="65%" align="center"></p>
    <!-- <p><img src="/icon/head2.jpg" align="middle" style="alignment-adjust: middle" ></p> -->
    
    <!--
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse
      </div>
    </nav> -->
      
      <?php echo $this->layout()->content; ?>
      
      <!-- Bootstrap core JavaScript
    ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
      <script src="/js/bootstrap.min.js"></script>
      
      <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
      <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
    <!--</p>-->
  </body>
  <footer>
     <table width="100%" border="0" align="center">
      <tr>
        <td align="center" style="color: black;text-align: center;font-family: Conv_FreesiaUPC; font-size: large" bgcolor="lightgray">
        	<p> Copyright©2016 All rights reserved by RFS Co.,Ltd.(Ramathibodi Facilities Services) </p>
        	<p> 270 Somdech Phra Debaratana Building, Ramathibodi Hospital, Rama VI Road, Thung Phayathai, Ratchathewi, BKK 10400 Tel. 0-2688-6555  Fax. 0-2688-6556</p>
        </td>
      </tr>
    </table>
  </footer>
</html>
